# Generated by Django 4.0.3 on 2022-03-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_song_singer1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer1',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
