# Generated by Django 4.0.3 on 2022-03-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_song_singer1_delete_singer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='cloths',
        ),
    ]
